[package]
name = "rusty_picture_namer_gui"
version = "1.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.2"
time = "0.3.7"
eframe = "0.18.0"
rfd = "0.8.2"
